# Generated by Django 5.0.6 on 2026-07-27 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesenvolvidorSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Desenvolvidor do site', max_length=200, verbose_name='Nome')),
                ('informacoes', models.TextField(blank=True, verbose_name='Informações do desenvolvedor')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Desenvolvidor do site',
                'verbose_name_plural': 'Desenvolvidor do site',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('categoria', models.CharField(choices=[('REGULAMENTO', 'Regulamento'), ('VITRINE', 'Vitrine / Novidades')], max_length=20, verbose_name='Categoria')),
                ('ficheiro', models.FileField(upload_to='documentos/%Y/%m/', verbose_name='Ficheiro')),
                ('publicado_em', models.DateTimeField(auto_now_add=True, verbose_name='Publicado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-publicado_em'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('cargo', models.CharField(max_length=150, verbose_name='Cargo')),
                ('desde', models.DateField(verbose_name='Desde')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='funcionarios/', verbose_name='Foto')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('disciplinas', models.CharField(blank=True, max_length=200, verbose_name='Disciplinas')),
                ('turma', models.CharField(blank=True, max_length=100, verbose_name='Turma')),
                ('periodo', models.CharField(blank=True, max_length=100, verbose_name='Período')),
                ('entrada', models.CharField(blank=True, max_length=20, verbose_name='Entrada')),
                ('saida', models.CharField(blank=True, max_length=20, verbose_name='Saída')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ImagemGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('categoria', models.CharField(choices=[('LAZER', 'Lazer'), ('HORARIO', 'Horário')], max_length=20, verbose_name='Categoria')),
                ('imagem', models.ImageField(upload_to='galeria/%Y/%m/', verbose_name='Imagem')),
                ('publicado_em', models.DateTimeField(auto_now_add=True, verbose_name='Publicado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': 'Imagens',
                'ordering': ['-publicado_em'],
            },
        ),
        migrations.CreateModel(
            name='Trabalhador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=30, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Trabalhador',
                'verbose_name_plural': 'Trabalhadores',
            },
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corpo_mensagem', models.TextField(help_text='Texto que informa a falta. O link individual é acrescentado automaticamente.', max_length=459, verbose_name='Corpo da mensagem')),
                ('ip_criacao', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origem')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comunicado de falta',
                'verbose_name_plural': 'Comunicados de falta',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Contributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Opcional', max_length=150, verbose_name='Nome')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('lido', models.BooleanField(default=False, verbose_name='Lido')),
                ('resposta', models.TextField(blank=True, verbose_name='Resposta do administrador')),
                ('respondido_em', models.DateTimeField(blank=True, null=True, verbose_name='Respondido em')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributos', to='escola.funcionario', verbose_name='Enviado a partir do perfil de')),
            ],
            options={
                'verbose_name': 'Contributo',
                'verbose_name_plural': 'Contributos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Destinatario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('estado_envio', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado'), ('FALHOU', 'Falhou')], default='PENDENTE', max_length=20)),
                ('resposta_gateway', models.CharField(blank=True, max_length=2000)),
                ('enviado_em', models.DateTimeField(blank=True, null=True)),
                ('acedido_em', models.DateTimeField(blank=True, null=True)),
                ('ip_acesso', models.GenericIPAddressField(blank=True, null=True)),
                ('comunicado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='escola.comunicado')),
                ('trabalhador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='escola.trabalhador')),
            ],
            options={
                'verbose_name': 'Destinatário',
                'verbose_name_plural': 'Destinatários',
            },
        ),
    ]
