# Generated by Django 5.0.6 on 2026-07-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='senha_pin',
            field=models.CharField(blank=True, default='', help_text='Senha de 3 dígitos que o funcionário usa para confirmar identidade antes de enviar mensagens à direção.', max_length=3, verbose_name='Senha (3 dígitos)'),
        ),
    ]
