# Generated by Django 5.0.6 on 2026-08-02 10:46

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_funcionario_senha_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='ficheiro',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documentos/%Y/%m/', verbose_name='Ficheiro'),
        ),
    ]
