# Generated by Django 5.0.6 on 2026-08-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0003_alter_documento_ficheiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributo',
            name='anexo',
            field=models.FileField(blank=True, help_text='Opcional. Aceita fotos ou ficheiros PDF.', null=True, upload_to='contributos/%Y/%m/', verbose_name='Foto ou documento (PDF)'),
        ),
        migrations.AlterField(
            model_name='contributo',
            name='mensagem',
            field=models.TextField(blank=True, verbose_name='Mensagem'),
        ),
    ]
