# Generated by Django 5.0.6 on 2026-08-02 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0004_contributo_anexo_alter_contributo_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemgaleria',
            name='mensagem',
            field=models.TextField(blank=True, help_text='Opcional. Explica o contexto da foto para quem for ver.', verbose_name='Mensagem sobre a foto'),
        ),
    ]
