# Generated by Django 5.0.6 on 2026-08-02 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0005_imagemgaleria_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='mensagem',
            field=models.TextField(blank=True, help_text='Opcional. Explica o contexto do documento para quem for ver.', verbose_name='Mensagem sobre o documento'),
        ),
    ]
