# Generated by Django 5.0.6 on 2026-08-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0006_documento_mensagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributo',
            name='resposta_vista',
            field=models.BooleanField(default=False, verbose_name='Resposta vista pelo funcionário'),
        ),
    ]
