# Generated by Django 5.0.6 on 2026-08-06 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0007_contributo_resposta_vista'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemInterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('anexo', models.FileField(blank=True, help_text='Opcional. Aceita fotos ou ficheiros PDF.', null=True, upload_to='mensagens_internas/%Y/%m/', verbose_name='Foto ou documento')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_recebidas', to='escola.funcionario', verbose_name='Para')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_enviadas', to='escola.funcionario', verbose_name='De')),
            ],
            options={
                'verbose_name': 'Mensagem entre Funcionários',
                'verbose_name_plural': 'Mensagens entre Funcionários',
                'ordering': ['criado_em'],
            },
        ),
    ]
