# Generated by Django 5.0.6 on 2026-08-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0008_mensageminterna'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensageminterna',
            name='lida',
            field=models.BooleanField(default=False, verbose_name='Lida pelo destinatário'),
        ),
    ]
