# Generated by Django 5.0.6 on 2026-08-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0009_mensageminterna_lida'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='classe',
            field=models.CharField(blank=True, max_length=100, verbose_name='Classe'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='sala',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sala'),
        ),
    ]
