# Generated by Django 5.0.6 on 2026-08-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0010_funcionario_classe_funcionario_sala'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desenvolvidorsite',
            options={'verbose_name': 'Histórico da Escola', 'verbose_name_plural': 'Histórico da Escola'},
        ),
        migrations.AlterField(
            model_name='documento',
            name='categoria',
            field=models.CharField(choices=[('REGULAMENTO', 'Regulamento'), ('VITRINE', 'Vitrine / Novidades'), ('MUSEU', 'Museu da Escola')], max_length=20, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='imagemgaleria',
            name='categoria',
            field=models.CharField(choices=[('LAZER', 'Lazer'), ('HORARIO', 'Horário'), ('MUSEU', 'Museu da Escola')], max_length=20, verbose_name='Categoria'),
        ),
    ]
