# Generated by Django 5.0.6 on 2026-08-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0011_alter_desenvolvidorsite_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinatario',
            name='comunicado',
        ),
        migrations.RemoveField(
            model_name='destinatario',
            name='trabalhador',
        ),
        migrations.DeleteModel(
            name='Comunicado',
        ),
        migrations.DeleteModel(
            name='Destinatario',
        ),
        migrations.DeleteModel(
            name='Trabalhador',
        ),
    ]
