# Generated by Django 5.0.6 on 2026-09-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0012_remove_destinatario_comunicado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='senha_pin',
            field=models.CharField(blank=True, default='', help_text='Senha de até 20 caracteres que o funcionário usa para confirmar identidade antes de enviar mensagens à direção.', max_length=20, verbose_name='Senha (até 20 caracteres)'),
        ),
    ]
