# Generated by Django 5.0.6 on 2026-09-17 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0014_mensagemdirecao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MensagemDirecao',
        ),
    ]
