# Generated by Django 5.0.6 on 2026-09-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0015_delete_mensagemdirecao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributo',
            name='resposta_anexo',
            field=models.FileField(blank=True, help_text='Opcional. Aceita fotos ou ficheiros PDF para enviar junto com a resposta.', null=True, upload_to='respostas_contributos/%Y/%m/', verbose_name='Foto ou documento da resposta'),
        ),
    ]
