# Generated by Django 5.0.6 on 2026-09-21 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0016_contributo_resposta_anexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemDirecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(blank=True, verbose_name='Mensagem')),
                ('anexo', models.FileField(blank=True, help_text='Opcional. Aceita fotos ou ficheiros PDF.', null=True, upload_to='mensagens_direcao/%Y/%m/', verbose_name='Foto ou documento (PDF)')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('lida', models.BooleanField(default=False, verbose_name='Lida pelo funcionário')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens_direcao', to='escola.funcionario', verbose_name='Para')),
            ],
            options={
                'verbose_name': 'Mensagem da Direção',
                'verbose_name_plural': 'Mensagens da Direção',
                'ordering': ['-criado_em'],
            },
        ),
    ]
